namespace: capz-system

namePrefix: capz-

# Labels to add to all resources and selectors.

resources:
- ../../config/manager
- ../../config/rbac



apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: infrastructure-azure
patches:
- path: patch_service_account.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: patch_healthcheck.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: ../../config/default/manager_image_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- path: ../../config/default/manager_pull_policy.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- path: ../../config/default/manager_credentials_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: base-manager-role
    path: patch_base_manager_role.yaml
