namespace: capi-webhook-system

namePrefix: capz-

resources:
- ../../config/default/namespace.yaml
- ../../config/default/aad-pod-identity-deployment.yaml
- ../../config/crd
- ../../config/webhook
- ../../config/manager
- ../../config/certmanager
- webhook_rbac.yaml


components:
- ../../config/aso

configurations:
- ../../config/default/kustomizeconfig.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: infrastructure-azure
patches:
- path: patch_cluster_role.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: aad-pod-id-nmi-role
    version: v1
- path: patch_namespace.yaml
  target:
    kind: Namespace
    name: system
    version: v1
- path: patch_aso_controller_settings.yaml
  target:
    kind: Secret
    name: aso-controller-settings
    version: v1
- path: patch_service_account.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: patch_service_account.yaml
  target:
    group: apps
    kind: DaemonSet
    name: nmi
    version: v1
- path: patch_nmi_cluster_role_binding.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: aad-pod-id-nmi-binding
    version: v1
- path: ../../config/default/manager_image_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- path: ../../config/default/manager_pull_policy.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- path: ../../config/default/manager_webhook_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- path: ../../config/default/mutatingwebhookcainjection_patch.yaml
  target:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
    version: v1
- path: ../../config/default/validatingwebhookcainjection_patch.yaml
  target:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
    version: v1
- path: patch_aso_metrics_service.yaml
  target:
    kind: Service
    name: azureserviceoperator-controller-manager-metrics-service
    version: v1
- path: patch_aso_metrics_service.yaml
  target:
    kind: Service
    name: azureserviceoperator-webhook-service
    version: v1
- path: patch_aso_controller_manager.yaml
  target:
    kind: Deployment
    name: azureserviceoperator-controller-manager
    version: v1
- path: patch_aso_webhook_annotations.yaml
  target:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: azureserviceoperator-mutating-webhook-configuration
    version: v1
- path: patch_aso_webhook_annotations.yaml
  target:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: azureserviceoperator-validating-webhook-configuration
    version: v1

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedclustertemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedcontrolplanes.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedmachinepools.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureasomanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedclustertemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclusteridentities.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachines.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinetemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinepools.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinepoolmachines.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_conversion.yaml
  - target:
      version: v1
      kind: Service
      name: azureserviceoperator-controller-manager-metrics-service
    patch: |-
      - op: remove
        path: /metadata/labels/cluster.x-k8s.io~1provider
      - op: remove
        path: /spec/selector/cluster.x-k8s.io~1provider

  - target:
      version: v1
      kind: Service
      name: azureserviceoperator-webhook-service
    patch: |-
      - op: remove
        path: /metadata/labels/cluster.x-k8s.io~1provider
      - op: remove
        path: /spec/selector/cluster.x-k8s.io~1provider

  - target:
        version: v1
        kind: Deployment
        name: azureserviceoperator-controller-manager
    patch: |-
      - op: remove
        path: /metadata/labels/cluster.x-k8s.io~1provider
      - op: remove
        path: /spec/selector/matchLabels/cluster.x-k8s.io~1provider
      - op: remove
        path: /spec/template/metadata/labels/cluster.x-k8s.io~1provider

replacements:
- source: # CERTIFICATE_NAMESPACE for all non-ASO resources with cert-manager annotation
    fieldPath: metadata.namespace
    kind: Certificate
    name: serving-cert
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
    select:
      annotationSelector: cert-manager.io/inject-ca-from
    reject:
    - labelSelector: app.kubernetes.io/name=azure-service-operator
    - kind: MutatingWebhookConfiguration
      name: azureserviceoperator-mutating-webhook-configuration
    - kind: ValidatingWebhookConfiguration
      name: azureserviceoperator-validating-webhook-configuration
- source: # CERTIFICATE_NAME for all non-ASO resources with cert-manager annotation
    kind: Certificate
    name: serving-cert
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
    select:
      annotationSelector: cert-manager.io/inject-ca-from
    reject:
    - labelSelector: app.kubernetes.io/name=azure-service-operator
    - kind: MutatingWebhookConfiguration
      name: azureserviceoperator-mutating-webhook-configuration
    - kind: ValidatingWebhookConfiguration
      name: azureserviceoperator-validating-webhook-configuration
- source: # CERTIFICATE_NAMESPACE for ASO resources
    fieldPath: metadata.namespace
    kind: Certificate
    name: azureserviceoperator-serving-cert
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
    select:
      annotationSelector: cert-manager.io/inject-ca-from
      labelSelector: app.kubernetes.io/name=azure-service-operator
- source: # CERTIFICATE_NAME for ASO resources
    kind: Certificate
    name: azureserviceoperator-serving-cert
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
    select:
      annotationSelector: cert-manager.io/inject-ca-from
      labelSelector: app.kubernetes.io/name=azure-service-operator
- source: # Update DNS names namespace in ASO certificate
    fieldPath: metadata.namespace
    kind: Service
    name: azureserviceoperator-webhook-service
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: azureserviceoperator-serving-cert
      version: v1
- source: # Update DNS names service name in ASO certificate
    kind: Service
    name: azureserviceoperator-webhook-service
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 0
    select:
      group: cert-manager.io
      kind: Certificate
      name: azureserviceoperator-serving-cert
      version: v1
